<?php
/**
 *  View for Link controller
 *  Copernica Marketing Software v 1.2.0
 *  March 2011
 *  http://www.copernica.com/
 */
$_helper = Mage::helper('marketingsoftware');
$_config = Mage::helper('marketingsoftware/config') ?>

<div class="content-header">
    <h3 class="icon-head head-system-account">Copernica Marketing Software : Link Fields</h3>
    <p class="content-buttons">
        <span id="cp_warning_notice" style="color: white; font-weight: bold; padding: 2px 4px; background-color: #CC3300; border: thin solid #660000; display:none;">Warning: the field settings are not valid !</span>        
        <span id="cp_save_notice" style="color: white; font-weight: bold; padding: 2px 4px; background-color: #188F11; border: thin solid #660000; display:none;">Warning: the settings are not yet saved !</span>
        <button type="button" onclick="cpProfileCollectionForm.submit();" name="cp_pc_save" id="cp_pc_save">Save profile and collections settings</button>
    </p>
</div>

<div class="entry-edit">

    <!-- fields linking form. -->
    <form action="<?php echo $this->getPostUrl(); ?>" method="post" name="cp_profile_collection" id="cp_profile_collection">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <!-- database checker section. -->        
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Database</h4>
            <a href="#" onclick ="document.getElementById('database_help').style.display='block'; return false;" id="page-help-link" style="float: right; line-height:18px;">More information</a>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="value">Name</td>
                            <td class="value">Status</td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text validate-code" value="<?php echo(htmlspecialchars($_config->getDatabaseName())); ?>" name="db_input" id="db_input"/>
                            </td>
                            <td class="value">
                                <span style="display:none;" id="db_checking">Checking database....</span>
                                <span style="display:none;" id="db_impossible">Database can not be checked.</span>
                                <span style="display:none;" id="db_notexists">Database does not exist. <a href="javascript:database.create()">Create database.</a></span>
                                <span style="display:none;" id="db_notvalid">Database structure not valid. <a href="javascript:database.repair()">Fix structure.</a></span>
                                <span style="display:none;" id="db_ok">Database exists.</span>
                            </td>                          
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end of database checker section. -->

        <!-- first section: customer profiles. -->
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend" id="customers_profiles_label" name="customers_profiles_label">Customers Profiles</h4>
            <a href="#" onclick ="document.getElementById('profiles_help').style.display='block'; return false;" id="page-help-link" style="float: right; line-height:18px;">More information</a>            
        </div>
        
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                        <td class="value">Magento field</td>
                        <td class="value">Copernica link</td>
                        <td class="value">Copernica field</td>
                        <td class="value">Status</td>
                        </tr>
                        <?php
                        // get the linked Customer fields
                        $linkedFields = $_config->getLinkedCustomerFields();
                        $customerFields = array();
                        
                        foreach ($_helper->supportedCustomerFields() as $magentoField => $label)
                        {
                            // Get the field which is used in Copernica
                            $copernicaField = isset($linkedFields[$magentoField]) ? $linkedFields[$magentoField] : '';
                            
                            // append a prefix to the customer
                            $magentoField = 'customer_'.$magentoField;
                            
                            // Create an array for using in javascript
                            $customerFields[$magentoField] = $copernicaField;
                            
                            // Name for the dropdown field, and name for the textfield
                            $dropdown_name = "select_$magentoField";
                            $textfield_name = "input_$magentoField";
                        ?>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text disabled" value="<?php echo(htmlspecialchars($label)); ?>" name="<?php echo(htmlspecialchars($label)); ?>" disabled="disabled" />
                            </td>
                            <td class="value">
                                <select class="select" id="<?php echo htmlspecialchars($dropdown_name); ?>" name="<?php echo htmlspecialchars($dropdown_name); ?>">
                                    <option value="0">Don't link</option>
                                    <option value="1" <?php if ($copernicaField != '') echo "selected='selected'"; ?>>Create link</option>
                                    <option value="2">Use default name</option>
                                </select>
                            </td>
                            <td class="value">
                                <input type="text" class="input-text validate-code" value="<?php echo htmlspecialchars($copernicaField); ?>" name="<?php echo htmlspecialchars($textfield_name); ?>" id="<?php echo htmlspecialchars($textfield_name); ?>" <?php if ($copernicaField == '') echo "style='display: none;'"; ?>>
                            </td>
                            <td class="value">
                                <span style="display:none;" id="checking_<?php echo $magentoField; ?>">Checking field....</span>
                                <span style="display:none;" id="impossible_<?php echo $magentoField; ?>">Field cannot be checked.</span>
                                <span style="display:none;" id="notexists_<?php echo $magentoField; ?>">Field does not exist. <a href="javascript:database.field('<?php echo $magentoField; ?>').create()">Create field.</a></span>
                                <span style="display:none;" id="notlinked_<?php echo $magentoField; ?>">Field is not linked.</a></span>
                                <span style="display:none;" id="notvalid_<?php echo $magentoField; ?>">Field is not valid. <a href="javascript:database.field('<?php echo $magentoField; ?>').repair()">Repair field.</a></span>
                                <span style="display:none;" id="ok_<?php echo $magentoField; ?>">Field exists.</span>
                            </td>                            
                        </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
<!-- end of first section. -->

<!-- second section: cart products collection. -->   
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend" id="edit_cartproducts_collection_current_label" name="edit_cartproducts_collection_current_label">Cart items Collection</h4>
            <a href="#" onclick ="document.getElementById('collection_help').style.display='block'; return false;" id="page-help-link" style="float: right; line-height:18px;">More information</a>            
        </div>
       <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="value">Collection name</td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text validate-code" title="Cart Products Collection" value="<?php echo(htmlspecialchars($_config->getCartItemsCollectionName())); ?>" name="cartproducts_input" id="cartproducts_input">
                            </td>
                            <td class="value">
                                <span style="display:none;" id="cartproducts_checking">Checking collection....</span>
                                <span style="display:none;" id="cartproducts_impossible">Collection cannot be checked.</span>
                                <span style="display:none;" id="cartproducts_notexists">Collection does not exist. <a href="javascript:database.cartItemsCollection.create()">Create collection.</a></span>
                                <span style="display:none;" id="cartproducts_notvalid">Collection structure not valid.<a href="javascript:database.cartItemsCollection.repair()">Repair collection.</a></span>
                                <span style="display:none;" id="cartproducts_ok">Collection exists.</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                        <td class="value">Magento field</td>
                        <td class="value">Copernica link</td>
                        <td class="value">Copernica field</td>
                        <td class="value">Status</td>
                        </tr>
                        <?php
                        // get the linked Customer fields
                        $linkedFields = $_config->getLinkedCartItemFields();
                        $cartItemFields = array();
                        
                        foreach ($_helper->supportedCartItemFields() as $magentoField => $label)
                        {
                            // Get the field which is used in Copernica
                            $copernicaField = isset($linkedFields[$magentoField]) ? $linkedFields[$magentoField] : '';

                            // append a prefix to the fieldname
                            $magentoField = 'cartproducts_'.$magentoField;
                            
                            // append the data to the array
                            $cartItemFields[$magentoField] = $copernicaField;
                            
                            // Name for the dropdown field, and name for the textfield
                            $dropdown_name = "select_$magentoField";
                            $textfield_name = "input_$magentoField";
                        ?>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text disabled" value="<?php echo(htmlspecialchars($label)); ?>" name="<?php echo(htmlspecialchars($label)); ?>" disabled="disabled" />
                            </td>
                            <td class="value">
                                <select class="select" id="<?php echo htmlspecialchars($dropdown_name); ?>" name="<?php echo htmlspecialchars($dropdown_name); ?>">
                                    <option value="0">Don't link</option>
                                    <option value="1" <?php if ($copernicaField != '') echo "selected='selected'"; ?>>Create link</option>
                                    <option value="2">Use default name</option>
                                </select>
                            </td>
                            <td class="value">
                                <input type="text" class="input-text validate-code" value="<?php echo htmlspecialchars($copernicaField); ?>" name="<?php echo htmlspecialchars($textfield_name); ?>" id="<?php echo htmlspecialchars($textfield_name); ?>" <?php if ($copernicaField == '') echo "style='display: none;'"; ?>>
                            </td>
                            <td class="value">
                                <span style="display:none;" id="checking_<?php echo $magentoField; ?>">Checking field....</span>
                                <span style="display:none;" id="impossible_<?php echo $magentoField; ?>">Field cannot be checked.</span>
                                <span style="display:none;" id="notexists_<?php echo $magentoField; ?>">Field does not exist. <a href="javascript:database.cartItemsCollection.field('<?php echo $magentoField; ?>').create()">Create field.</a></span>
                                <span style="display:none;" id="notlinked_<?php echo $magentoField; ?>">Field is not linked.</a></span>
                                <span style="display:none;" id="notvalid_<?php echo $magentoField; ?>">Field is not valid. <a href="javascript:database.cartItemsCollection.field('<?php echo $magentoField; ?>').repair()">Repair field.</a></span>
                                <span style="display:none;" id="ok_<?php echo $magentoField; ?>">Field exists.</span>
                            </td>                            
                        </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>        
<!-- end of second section. -->

<!-- third section: orders collection. -->           
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend" id="edit_orders_collection_current_label" name="edit_orders_collection_current_label">Orders Collection</h4>
            <a href="#" onclick ="document.getElementById('collection_help').style.display='block'; return false;" id="page-help-link" style="float: right; line-height:18px;">More information</a>            
        </div>
       <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="value">Collection name</td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text validate-code" title="Completed Orders Collection" value="<?php echo(htmlspecialchars($_config->getOrdersCollectionName())); ?>" name="orders_input" id="orders_input">
                            </td>
                            <td class="value">
                                <span style="display:none;" id="orders_checking">Checking collection....</span>
                                <span style="display:none;" id="orders_impossible">Collection cannot be checked.</span>
                                <span style="display:none;" id="orders_notexists">Collection does not exist. <a href="javascript:database.ordersCollection.create()">Create collection.</a></span>
                                <span style="display:none;" id="orders_notvalid">Collection structure not valid.<a href="javascript:database.ordersCollection.repair()">Repair collection.</a></span>
                                <span style="display:none;" id="orders_ok">Collection exists.</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>        
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                        <td class="value">Magento field</td>
                        <td class="value">Copernica link</td>
                        <td class="value">Copernica field</td>
                        <td class="value">Status</td>
                        </tr>
                        <?php
                        // get the linked Customer fields
                        $linkedFields = $_config->getLinkedOrderFields();
                        $orderFields = array();
                        
                        foreach ($_helper->supportedOrderFields() as $magentoField => $label)
                        {
                            // Get the field which is used in Copernica
                            $copernicaField = isset($linkedFields[$magentoField]) ? $linkedFields[$magentoField] : '';

                            // append a prefix to the fieldname
                            $magentoField = 'orders_'.$magentoField;
                            
                            // Construct an array for use in the javascript array
                            $orderFields[$magentoField] = $copernicaField;
                            
                            // Name for the dropdown field, and name for the textfield
                            $dropdown_name = "select_$magentoField";
                            $textfield_name = "input_$magentoField";
                        ?>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text disabled" value="<?php echo(htmlspecialchars($label)); ?>" name="<?php echo(htmlspecialchars($label)); ?>" disabled="disabled" />
                            </td>
                            <td class="value">
                                <select class="select" id="<?php echo htmlspecialchars($dropdown_name); ?>" name="<?php echo htmlspecialchars($dropdown_name); ?>">
                                    <option value="0">Don't link</option>
                                    <option value="1" <?php if ($copernicaField != '') echo "selected='selected'"; ?>>Create link</option>
                                    <option value="2">Use default name</option>
                                </select>
                            </td>
                            <td class="value">
                                <input type="text" class="input-text validate-code" value="<?php echo htmlspecialchars($copernicaField); ?>" name="<?php echo htmlspecialchars($textfield_name); ?>" id="<?php echo htmlspecialchars($textfield_name); ?>" <?php if ($copernicaField == '') echo "style='display: none;'"; ?>>
                            </td>
                            <td class="value">
                                <span style="display:none;" id="checking_<?php echo $magentoField; ?>">Checking field....</span>
                                <span style="display:none;" id="impossible_<?php echo $magentoField; ?>">Field cannot be checked.</span>
                                <span style="display:none;" id="notexists_<?php echo $magentoField; ?>">Field does not exist. <a href="javascript:database.ordersCollection.field('<?php echo $magentoField; ?>').create()">Create field.</a></span>
                                <span style="display:none;" id="notlinked_<?php echo $magentoField; ?>">Field is not linked.</a></span>
                                <span style="display:none;" id="notvalid_<?php echo $magentoField; ?>">Field is not correct. <a href="javascript:database.ordersCollection.field('<?php echo $magentoField; ?>').repair()">Repair field.</a></a></span>
                                <span style="display:none;" id="ok_<?php echo $magentoField; ?>">Field exists.</span>
                            </td>                            
                        </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
<!-- end of third section. -->

<!-- fourth section: orders products collection. -->   
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend" id="edit_orderproducts_collection_current_label" name="edit_orderproducts_collection_current_label">Order products Collection</h4>
            <a href="#" onclick ="document.getElementById('collection_help').style.display='block'; return false;" id="page-help-link" style="float: right; line-height:18px;">More information</a>            
        </div>
       <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="value">Collection name</td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text validate-code" title="Cart Products Collection" value="<?php echo(htmlspecialchars($_config->getOrderItemsCollectionName()))?>" name="orderproducts_input" id="orderproducts_input">
                            </td>
                            <td class="value">
                                <span style="display:none;" id="orderproducts_checking">Checking collection....</span>
                                <span style="display:none;" id="orderproducts_impossible">Collection cannot be checked.</span>
                                <span style="display:none;" id="orderproducts_notexists">Collection does not exist. <a href="javascript:database.orderItemsCollection.create()">Create collection.</a></span>
                                <span style="display:none;" id="orderproducts_notvalid">Collection structure not valid.<a href="javascript:database.orderItemsCollection.repair()">Repair collection.</a></span>
                                <span style="display:none;" id="orderproducts_ok">Collection exists.</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                        <td class="value">Magento field</td>
                        <td class="value">Copernica link</td>
                        <td class="value">Copernica field</td>
                        <td class="value">Status</td>
                        </tr>
                        <?php
                        // get the linked Customer fields
                        $linkedFields = $_config->getLinkedOrderItemFields();
                        $orderItemFields = array();
                        
                        foreach ($_helper->supportedOrderItemFields() as $magentoField => $label)
                        {
                            // Get the field which is used in Copernica
                            $copernicaField = isset($linkedFields[$magentoField]) ? $linkedFields[$magentoField] : '';

                            // append a prefix to the fieldname
                            $magentoField = 'orderproducts_'.$magentoField;
                            
                            // Construct an array for use in the javascript array
                            $orderItemFields[$magentoField] = $copernicaField;
                            
                            // Name for the dropdown field, and name for the textfield
                            $dropdown_name = "select_$magentoField";
                            $textfield_name = "input_$magentoField";
                        ?>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text disabled" value="<?php echo(htmlspecialchars($label)); ?>" name="<?php echo(htmlspecialchars($label)); ?>" disabled="disabled" />
                            </td>
                            <td class="value">
                                <select class="select" id="<?php echo htmlspecialchars($dropdown_name); ?>" name="<?php echo htmlspecialchars($dropdown_name); ?>">
                                    <option value="0">Don't link</option>
                                    <option value="1" <?php if ($copernicaField != '') echo "selected='selected'"; ?>>Create link</option>
                                    <option value="2">Use default name</option>
                                </select>
                            </td>
                            <td class="value">
                                <input type="text" class="input-text validate-code" value="<?php echo htmlspecialchars($copernicaField); ?>" name="<?php echo htmlspecialchars($textfield_name); ?>" id="<?php echo htmlspecialchars($textfield_name); ?>" <?php if ($copernicaField == '') echo "style='display: none;'"; ?>>
                            </td>
                            <td class="value">
                                <span style="display:none;" id="checking_<?php echo $magentoField; ?>">Checking field....</span>
                                <span style="display:none;" id="impossible_<?php echo $magentoField; ?>">Field cannot be checked.</span>
                                <span style="display:none;" id="notexists_<?php echo $magentoField; ?>">Field does not exist. <a href="javascript:database.orderItemsCollection.field('<?php echo $magentoField; ?>').create()">Create field.</a></span>
                                <span style="display:none;" id="notlinked_<?php echo $magentoField; ?>">Field is not linked.</a></span>
                                <span style="display:none;" id="notvalid_<?php echo $magentoField; ?>">Field is not valid. <a href="javascript:database.orderItemsCollection.field('<?php echo $magentoField; ?>').repair()">Repair field.</a></span>
                                <span style="display:none;" id="ok_<?php echo $magentoField; ?>">Field exists.</span>
                            </td>                            
                        </tr>
                        <?php
                            }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>        
<!-- end of fourth section. -->

<!-- fifth section: address collection. -->           
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend" id="edit_addresses_collection_current_label" name="edit_addresscollection_current_label">Address Collection</h4>
            <a href="#" onclick ="document.getElementById('collection_help').style.display='block'; return false;" id="page-help-link" style="float: right; line-height:18px;">More information</a>            
        </div>
       <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="value">Collection name</td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text validate-code" title="Completed Orders Collection" value="<?php echo(htmlspecialchars($_config->getAddressesCollectionName()))?>" name="addresses_input" id="addresses_input">
                            </td>
                            <td class="value">
                                <span style="display:none;" id="addresses_checking">Checking collection....</span>
                                <span style="display:none;" id="addresses_impossible">Collection cannot be checked.</span>
                                <span style="display:none;" id="addresses_notexists">Collection does not exist. <a href="javascript:database.addressCollection.create()">Create collection.</a></span>
                                <span style="display:none;" id="addresses_notvalid">Collection structure not valid.<a href="javascript:database.addressCollection.repair()">Repair collection.</a></span>
                                <span style="display:none;" id="addresses_ok">Collection exists.</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>        
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                        <td class="value">Magento field</td>
                        <td class="value">Copernica link</td>
                        <td class="value">Copernica field</td>
                        <td class="value">Status</td>
                        </tr>
                        <?php
                        // get the linked Customer fields
                        $linkedFields = $_config->getLinkedAddressFields();
                        
                        $addressFields = array();
                        
                        foreach ($_helper->supportedAddressFields() as $magentoField => $label)
                        {
                            // Get the field which is used in Copernica
                            $copernicaField = isset($linkedFields[$magentoField]) ? $linkedFields[$magentoField] : '';

                            // append a prefix to the fieldname
                            $magentoField = 'addresses_'.$magentoField;
                            
                            // Construct an array for use in the javascript array
                            $addressFields[$magentoField] = $copernicaField;
                            
                            // Name for the dropdown field, and name for the textfield
                            $dropdown_name = "select_$magentoField";
                            $textfield_name = "input_$magentoField";
                        ?>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text disabled" value="<?php echo(htmlspecialchars($label)); ?>" name="<?php echo(htmlspecialchars($label)); ?>" disabled="disabled" />
                            </td>
                            <td class="value">
                                <select class="select" id="<?php echo htmlspecialchars($dropdown_name); ?>" name="<?php echo htmlspecialchars($dropdown_name); ?>">
                                    <option value="0">Don't link</option>
                                    <option value="1" <?php if ($copernicaField != '') echo "selected='selected'"; ?>>Create link</option>
                                    <option value="2">Use default name</option>
                                </select>
                            </td>
                            <td class="value">
                                <input type="text" class="input-text validate-code" value="<?php echo htmlspecialchars($copernicaField); ?>" name="<?php echo htmlspecialchars($textfield_name); ?>" id="<?php echo htmlspecialchars($textfield_name); ?>" <?php if ($copernicaField == '') echo "style='display: none;'"; ?>>
                            </td>
                            <td class="value">
                                <span style="display:none;" id="checking_<?php echo $magentoField; ?>">Checking field....</span>
                                <span style="display:none;" id="impossible_<?php echo $magentoField; ?>">Field cannot be checked.</span>
                                <span style="display:none;" id="notexists_<?php echo $magentoField; ?>">Field does not exist. <a href="javascript:database.addressCollection.field('<?php echo $magentoField; ?>').create()">Create field.</a></span>
                                <span style="display:none;" id="notlinked_<?php echo $magentoField; ?>">Field is not linked.</a></span>
                                <span style="display:none;" id="notvalid_<?php echo $magentoField; ?>">Field is not valid. <a href="javascript:database.addressCollection.field('<?php echo $magentoField; ?>').repair()">Repair field.</a></span>
                                <span style="display:none;" id="ok_<?php echo $magentoField; ?>">Field exists.</span>
                            </td>                            
                        </tr>
                        <?php
                            }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
<!-- end of fifth section. -->
        
<!-- sixt section: viewed product collection. -->   
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend" id="edit_viewedproduct_collection_current_label" name="edit_viewedproduct_collection_current_label">Viewed product Collection</h4>
            <a href="#" onclick ="document.getElementById('collection_help').style.display='block'; return false;" id="page-help-link" style="float: right; line-height:18px;">More information</a>            
        </div>
       <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="value">Collection name</td>
                        </tr>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text validate-code" title="Viewed Product Collection" value="<?php echo(htmlspecialchars($_config->getViewedProductCollectionName())); ?>" name="viewedproduct_input" id="viewedproduct_input">
                            </td>
                            <td class="value">
                                <span style="display:none;" id="viewedproduct_checking">Checking collection....</span>
                                <span style="display:none;" id="viewedproduct_impossible">Collection cannot be checked.</span>
                                <span style="display:none;" id="viewedproduct_notexists">Collection does not exist. <a href="javascript:database.viewedProductCollection.create()">Create collection.</a></span>
                                <span style="display:none;" id="viewedproduct_notvalid">Collection structure not valid.<a href="javascript:database.viewedProductCollection.repair()">Repair collection.</a></span>
                                <span style="display:none;" id="viewedproduct_ok">Collection exists.</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                        <td class="value">Magento field</td>
                        <td class="value">Copernica link</td>
                        <td class="value">Copernica field</td>
                        <td class="value">Status</td>
                        </tr>
                        <?php
                        // get the linked Customer fields
                        $linkedFields = $_config->getLinkedViewedProductFields();
                        $viewedProductFields = array();
                        
                        foreach ($_helper->supportedViewedProductFields() as $magentoField => $label)
                        {
                            // Get the field which is used in Copernica
                            $copernicaField = isset($linkedFields[$magentoField]) ? $linkedFields[$magentoField] : '';

                            // append a prefix to the fieldname
                            $magentoField = 'viewedproduct_'.$magentoField;
                            
                            // append the data to the array
                            $viewedProductFields[$magentoField] = $copernicaField;
                            
                            // Name for the dropdown field, and name for the textfield
                            $dropdown_name = "select_$magentoField";
                            $textfield_name = "input_$magentoField";
                        ?>
                        <tr>
                            <td class="value">
                                <input type="text" class="input-text disabled" value="<?php echo(htmlspecialchars($label)); ?>" name="<?php echo(htmlspecialchars($label)); ?>" disabled="disabled" />
                            </td>
                            <td class="value">
                                <select class="select" id="<?php echo htmlspecialchars($dropdown_name); ?>" name="<?php echo htmlspecialchars($dropdown_name); ?>">
                                    <option value="0">Don't link</option>
                                    <option value="1" <?php if ($copernicaField != '') echo "selected='selected'"; ?>>Create link</option>
                                    <option value="2">Use default name</option>
                                </select>
                            </td>
                            <td class="value">
                                <input type="text" class="input-text validate-code" value="<?php echo htmlspecialchars($copernicaField); ?>" name="<?php echo htmlspecialchars($textfield_name); ?>" id="<?php echo htmlspecialchars($textfield_name); ?>" <?php if ($copernicaField == '') echo "style='display: none;'"; ?>>
                            </td>
                            <td class="value">
                                <span style="display:none;" id="checking_<?php echo $magentoField; ?>">Checking field....</span>
                                <span style="display:none;" id="impossible_<?php echo $magentoField; ?>">Field cannot be checked.</span>
                                <span style="display:none;" id="notexists_<?php echo $magentoField; ?>">Field does not exist. <a href="javascript:database.viewedProductCollection.field('<?php echo $magentoField; ?>').create()">Create field.</a></span>
                                <span style="display:none;" id="notlinked_<?php echo $magentoField; ?>">Field is not linked.</a></span>
                                <span style="display:none;" id="notvalid_<?php echo $magentoField; ?>">Field is not valid. <a href="javascript:database.viewedProductCollection.field('<?php echo $magentoField; ?>').repair()">Repair field.</a></span>
                                <span style="display:none;" id="ok_<?php echo $magentoField; ?>">Field exists.</span>
                            </td>                            
                        </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>        
<!-- end of sixt section. -->

    </form>
<!-- end of fields linking form. -->

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Important Notice</h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                    <td>To enable the Magento extension, you need to have a valid license for <a href="https://www.copernica.com/en/magento" target="_blank" title="Copernica Marketing Software">Copernica Marketing Software</a>.</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Environment Information</h4>
    </div>
    <div class="fieldset">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                    <td class="label">Copernica extension version: </td>
                    <td class="value"><strong><?php echo $_helper->getExtensionVersion();?></strong></td>
                    </tr>
                    <tr>
                    <td class="label">Magento webshop version: </td>
                    <td class="value"><strong><?php echo Mage::getVersion();?></strong></td>
                    </tr>                    
                </tbody>
            </table>
        </div>
    </div>      
</div>

<!-- define the popup "More information" messages -->

<!-- database help -->
<div id="database_help" style="display: none; position: fixed; top: 30%; left: 30%; width: 580px; height: 385px; padding: 20px; border: 1px solid black; z-index:1002;background-color: #FDFAB1; color: black;">
    <h3 style="text-align: center;">Database HOW-TO</h3>
    Set your Copernica Database, which will be used for Magento shop information import.
    <br/><br/>
    You can type the name of your Copernica Database in the "Name" field.
    <br/><br/>
    If the Database exists, the "Status" will confirm with a "Database exists" message.
    <br/>
    Else, the "Status" will serve you a link to "Create Database" in your Copernica Environment, while not leaving this page.
    <br/>
    It is also possible that a Database can exist with the name you specified, but needed fields for the extension are not available in its structure.
    <br/>
    In this case, you will be provided with a link to "Repair the database". This operation will also be completed while not leaving this page.
    <br/><br/>
    [+] A "Database exists" status message confirms that you have a valid Database created in the Copernica environment and linked to be used with your Magento Webshop.
    <br/><br/>
    [+] Be sure to "Save profile and collections settings" after specifying new database details. You can do this by using the button in the top-right corner.
    <br/><br/>
    [+] Operations on this page can only be executed if we have a valid Copernica account connection, that was set on the "Account Settings" page, which can be found under the "Copernica Marketing Software" menu.
    <br/>
    <a href="#" onclick="document.getElementById('database_help').style.display='none'; return false;" style="top:0; right:6px; position: absolute;">Close</a>
</div>

<!-- profiles help -->
<div id="profiles_help" style="display: none; position: fixed; top: 30%; left: 30%; width: 600px; height: 420px; padding: 20px; border: 1px solid black; z-index:1002;background-color: #FDFAB1; color: black;">
    <h3 style="text-align: center;">Profiles HOW-TO</h3>
    Link Magento Customer fields to Copernica Profiles fields.
    <br/><br/>
    You can link or unlink any fields you wish, which are displayed in the "Customers profiles" section, on this page.
    <br/><br/>
    To link a certain field, select the "Create link" option from the "Copernica link" drop-down list, related to that field. 
    <br/>
    Further on, you need to label this field with your own value, inside the "Copernica field" textbox. The value should not be empty, should not contain spaces and should not start with a number.
    <br/><br/>
    If the field already exists in the Copernica Profiles structure, the "Status" will display a "Field exists" message.
    <br/>
    Else the "Status" will serve you a "Create field" link which can be used to create the field inside the Copernica Profiles structure, while not leaving this page.
    <br/><br/>
    To unlink a certain field, select the "Don't link" option from the "Copernica link" drop-down list, related to that field.
    <br/><br/>
    [+] A "Field exists" status message confirms that you have a valid field inside the Copernica Profiles structure, which can be used with the Magento linking system.
    <br/><br/>
    [+] Be sure to "Save profile and collections settings" after modifying the fields status and values. You can do this by using the button in the top-right corner.
    <br/><br/>
    [+] Operations on this page can only be executed if there is a valid Copernica account connection, that was set on the "Account Settings" page, which can be found under the "Copernica Marketing Software" menu.
    <br/>
    <a href="#" onclick="document.getElementById('profiles_help').style.display='none'; return false;" style="top:0; right:6px; position: absolute;">Close</a>
</div>

<!-- collection help -->
<div id="collection_help" style="display: none; position: fixed; top: 15%; left: 25%; width: 700px; height: 680px; padding: 20px; border: 1px solid black; z-index:1002;background-color: #FDFAB1; color: black;">
    <h3 style="text-align: center;">Collections HOW-TO</h3>
    Create Copernica Collections. Link Magento Products and Orders fields to Copernica Collections fields.
    <br/><br/>
    You can type the name of your Copernica Collection in the "Collection name" field.
    <br/><br/>
    If the Collection exists, the "Status" will confirm with a "Collection exists" message.
    <br/>
    Else, the "Status" will serve you a link to "Create Collection" in your Copernica Environment, while not leaving this page.
    <br/>
    It is also possible that a Collection can exist with the name you specified, but needed fields for the extension are not available in its structure.
    <br/>
    In this case, you will be provided with a link to "Repair collection". This operation will also be completed while not leaving this page.
    <br/><br/>
    You can link or unlink any fields you wish, which are displayed in the Collection sections, on this page.
    <br/><br/>
    To link a certain field, select the "Create link" option from the "Copernica link" drop-down list, related to that field. 
    <br/>
    Further on, you need to label this field with your own value, inside the "Copernica field" textbox. The value should not be empty, should not contain spaces and should not start with a number.
    <br/><br/>
    If the field already exists in the Copernica Collection structure, the "Status" will display a "Field exists" message.
    <br/>
    Else the "Status" will serve you a "Create field" link which can be used to create the field inside the Copernica Collection structure, while not leaving this page.
    <br/><br/>
    To unlink a certain field, select the "Don't link" option from the "Copernica link" drop-down list, related to that field.
    <br/><br/>
    [+] First collection section from this page is related to Products Collection. The second collection section is related to Orders Collection.
    <br/><br/>
    [+] A "Collection exists" status message confirms that you have a valid Collection created in the Copernica environment and linked to be used with your Magento Webshop.
    <br/><br/>
    [+] A "Field exists" status message confirms that you have a valid field inside the Copernica Profiles structure, which can be used with the Magento linking system.
    <br/><br/>
    [+] Be sure to "Save profile and collections settings" after modifying the fields status and values or specifying new collection details. You can do this by using the button in the top-right corner.
    <br/><br/>
    [+] Operations on this page can only be executed if there is a valid Copernica account connection, that was set on the "Account Settings" page, which can be found under the "Copernica Marketing Software" menu.
    <br/>
    <a href="#" onclick="document.getElementById('collection_help').style.display='none'; return false;" style="top:0; right:6px; position: absolute;">Close</a>
</div>

<script type="text/javascript">
/**
 *  Javascript variables with all database and collection fields
 *  @var array
 */
var customerFields = <?php echo(json_encode($customerFields)); ?>;
var cartItemFields = <?php echo(json_encode($cartItemFields)); ?>;
var orderFields = <?php echo(json_encode($orderFields)); ?>;
var orderItemFields = <?php echo(json_encode($orderItemFields)); ?>;
var addressFields = <?php echo(json_encode($addressFields)); ?>;
var viewedProductFields = <?php echo(json_encode($viewedProductFields)); ?>;

/**
 *  The main database object (that also does all initialisation)
 *  @var Database
 */
var database = new CopernicaDatabase();

// check all fields in the database
database.check();

/**
 *  Do an ajax call to the server
 *  @param  array       Data to send to the server
 *  @param  function    Callback function that will be called when the answer is received from the server
 */
function doAjaxCall(data, callback)
{
    // we define our processing URL
    var url = <?php echo(json_encode($this->getAjaxUrl())); ?>;
    
    // make the request, and decode the answer back from json
    new Ajax.Request(url, {
        method: 'post',
        parameters: data,
        onLoading: function() {
            $('loading-mask', 'loading_mask_loader').invoke('hide');
        },
        onComplete: function(answer) {
            callback(eval(answer));
        }
    });
}

//<![CDATA[
    var customForm = new VarienForm('cp_form', true);
    cpForm = new VarienForm('cp_form', '');
    cpProfileCollectionForm = new VarienForm('cp_profile_collection', '');

    document.observe('dom:loaded', function() {

    	$$('.input-text').forEach(function(e) {
    		Event.observe(e, 'change', function() {
    			cpProfileCollectionForm.validator.validate();
    		});
    	});
    });
//]]>
</script>